### ISSUE TITLE
Check if user voted for x items

### ISSUE THREAD

**Issue by Brotakuu** [bouchard/thumbs_up#109]
Is there a quick method to check if `current_user` has voted for any of `@items`. Return `true` or `false`.

**Comment by bouchard** [comment]
There's no custom method, but doing it yourself wouldn't be hard. Feel free to send a PR for an added method to `acts_as_voter.rb`:

```ruby
  def voteables_voted_for(voteable_class)
    v = Vote.where(
      :voter_id => self.id,
      :voter_type => self.class.base_class.name
      :voteable_type => voteable_class.class.base_class.name
    ).pluck(:voteable_id)
    voteable_class.where(id: v)
  end
```

And then you could use this method something like:

```ruby
  current_user.voteables_voted_for(Item)
```

or if you just want the boolean (additional method added to `acts_as_voter.rb`:

```ruby
  def any_voteables_voted_for?(voteable_class)
    self.voteables_voted_for(Item).count > 0
  end
```

**Comment by Brotakuu** [comment]
I'm currently doing something like this:
`@items.where('votes.voter_id' => current_user.id).any?`

Do you see any downside of doing it this way?

**Comment by bouchard** [comment]
I'm assuming `@items` is an AR Relation...

As long as you've got a `joins(:votes)` somewhere in there, that looks good to me. It would be clearer if you could post the SQL as well to see if it's generating it correctly.

**Comment by Brotakuu** [comment]
This is the query that it executes:

`SELECT COUNT(*) AS count_all, items.id AS items_id FROM "items" LEFT OUTER JOIN votes ON items.id = votes.voteable_id AND votes.voteable_type = 'Item' WHERE "items"."topic_id" = ? AND "votes"."voter_id" = 28 GROUP BY items.id  ORDER BY (COUNT(votes.vote) + items.admin_vote_count) DESC  [["topic_id", 18]]`

And yes, I'd be happy to add a PR if there are others that need this.

**Comment by bouchard** [comment]
Looks good! Thanks.
