### ISSUE TITLE
undefined local variable or method 'acts_as_voteable' for...

### ISSUE THREAD

**Issue by iam1492** [bouchard/thumbs_up#53]
Hi, thanks for your great work.

I currently have problem with some error only if I deploy with caspitrano to my ubuntu server.

I use nginx + unicorn in my deploy server and always shows me "undefined local variable or method 'acts_as_voteable' for..." 

Strange thing is when I use local rails server there is no problem(mac book with rails 3.2.7 and same ruby 1.9.3 version)

The error only shown in deploy server. I checked installed bundle(thumbs_up) with bundle list command and also checked database table exist correctly in deploy server side. 

Do you have any idea to solve this issue? or just advise me. 

I'm first at ruby on rails and nginx+unicorn. So this might be my configuration problem.

Thanks,
Wooram

**Comment by jfpineda84** [comment]
I'm running rails 5.1. I moved the `gem "acts_as_votable", "~> 0.10.0"` from the bottom to the top and it worked... not sure why
