### ISSUE TITLE
List of records a user has voted for

### ISSUE THREAD

**Issue by CiaranPearse** [bouchard/thumbs_up#99]
How would I show a list of posts that a user has voted for? I've been able to figure out every thing else except this (can show a list of users who voted on a post etc).

**Comment by gcrofils** [comment]
@posts = Post.tally.where('votes.voter_id' => user.id).where('voteable_type = ?', 'Post')

according to me `where('voteable_type = ?', 'Post')` must be integrated in `lib/acts_as_voteable.rb#tally(*args)`

**Comment by rchezrutt88** [comment]
@CiaranPearse I'm having the same issue. Did you ever figure it out?

**Comment by bouchard** [comment]
You're in luck, everyone (many months later): discuss and code here: https://github.com/bouchard/thumbs_up/issues/109
